# HTTP Version
server{
    listen 8080;
    server_name server.galatea.my;

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/shinqhwa/galatea/cognition/galatea.sock;
    }

    location ^~ /.well-known/acme-challenge/ {
        default_type "text/plain";
        root /var/www/letsencrypt;
    }
}

# HTTPS Version
server {
    listen 8080;
    server_name server.galatea.my;

    return 301 https://$host$request_uri;
}

server{
    listen 443 ssl;
    server_name server.galatea.my;

    ssl_certificate /etc/letsencrypt/live/server.galatea.my/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/server.galatea.my/privkey.pem;

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/shinqhwa/galatea/cognition/galatea.sock;
    }

    location ^~ /.well-known/acme-challenge/ {
        default_type "text/plain";
        root /var/www/letsencrypt;
    }
}