server {
    listen 2174 ssl;
    server_name server.galatea.my;

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/shinqhwa/galatea/cognition/galatea.sock;
    }

    ssl_certificate /etc/letsencrypt/live/server.galatea.my/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/server.galatea.my/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location ^~ /.well-known/acme-challenge/ {
        default_type "text/plain";
        root /var/www/letsencrypt;
    }
}

